#! /bin/bash
#a script to get the vaules of xinput id and props for tapping and use them

touchvar=$(xinput | grep TouchPad)


idstart=$(echo | awk '{print index("'"${touchvar}"'", "id")}')


idstart=$[ idstart = $idstart+3 ]

idvar=$(echo | awk '{print substr("'"${touchvar}"'","'"${idstart}"'",2)}')

tapvar=$(xinput list-props $idvar | grep Tapping\ Enabled)


propvar=$(expr substr "${tapvar}" 28 3)


if [ "$1" = 1 ]
	then
		xinput set-prop $idvar $propvar 1
fi

if [ "$1" = 0 ]
	then
		xinput set-prop $idvar $propvar 0
fi
