#!/usr/bin/env python2

import pynotify
import sys
import os
import string

if __name__ == '__main__':
    if not pynotify.init("jf-mpdstatus"):
        sys.exit(1)
    if len(sys.argv)==1:
        title = ""
        p = os.popen("mpc current -f %title% && mpc current -f %artist% && mpc current -f %album% && mpc current -f %date%","r")
        message = ""
        while 1:
            line = p.readline()
            if not line: break
            message = message + line
        x = os.popen("~/.scripts/coverart.sh","r")
        image = ""
        while 1:
            line = x.readline()
            if not line: break
            image = image + line
        n = pynotify.Notification(title, message, image)
        n.set_urgency(pynotify.URGENCY_LOW)
        n.set_timeout(10000)
        if not n.show():
            print "Failed to send notification"
            sys.exit(1)
        sys.exit()
